### PR TITLE
Routing reworked

### PR DESCRIPTION
**Pull request by jonasvoelcker**

### CODE REVIEW

**Comment by jonasvoelcker** [comment]
Hey @AlexisSouquiere, a first try to help a bit ;)

**Comment by jonasvoelcker** [comment]
@AlexisSouquiere Do you use MS Teams? This might make coordination easier.

**Comment by AlexisSouquiere** [comment]
@jonasvoelcker yes ! Here is my email: alexis.souquiere@michelin.com

**Comment by jonasvoelcker** [comment]
image

May you try? info@jonas-voelcker.de

**Pull request merged**
